name: Reusable workflow example

on:
  workflow_call:
    #inputs:
      #config-path:
        #required: false
        #type: string
    #secrets:
      #envPAT:
        #required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_teste_vars:
    runs-on: ubuntu-latest
    
    outputs:
      outputs1-VAR_OLA: ${{ steps.steps_var.outputs.VAR_OLA }}
    
    steps:
      - name: Set VAR_OLA
        id: steps_var
        run: |
          echo "VAR_OLA=ola" >> $GITHUB_OUTPUT
