name: Reusable workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      var_recebe_teste:
        required: true
        type: string
      var_recebe_environment:
        required: true
        type: string
#     secrets:
#       envPAT:
#         required: false

jobs:
  job_set_environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.var_recebe_environment }}

    steps:
      - name: Imprime vars
        run: |
          echo "${{ inputs.var_recebe_teste }}"    #input passado na chamada
          echo "${{ secrets.VAR_SECRETA_TESTE }}"  #var secreta criada no repo ou var sobreescrita pela mesma var secrets do environment
          echo "${{ secrets.VAR_SECRETA_TESTE2 }}" #var secreta criada no repo
          echo "${{ vars.VAR_ACTION }}"            #var normal criada no repo ENVIRONMENT_VAR
          echo "${{ vars.ENVIRONMENT_VAR }}"       #var normal criada no environment dev
